trigger:
  branches:
    include:
    - master

pool:
  name: Default
  vmImage: 'ubuntu-latest'
  demands:
    - android-sdk

variables:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false'
  JAVA_HOME: $(JAVA_HOME_11_X64)  # Use the appropriate variable for Java 11

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: 'Build and Test'
    steps:
    - script: echo "Running Gradle clean"
      displayName: 'Clean Build'
      
    - script: ./gradlew assembleDebug
      displayName: 'Assemble Debug Build'

    - script: ./gradlew test
      displayName: 'Run Unit Tests'
    
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-results/**/*.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)'
        mergeTestResults: true
        testRunTitle: 'Android Unit Tests'

    - task: Gradle@3
      inputs:
        gradleWrapperFile: 'gradlew'
        workingDirectory: '/'
        tasks: 'build'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: true
