trigger:
- master  # You can specify the branch to trigger the pipeline

pr:
- '*'

pool:
  vmImage: 'linux'
  demands:
    - xcode
    - android-sdk

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'
    addToPath: true

- script: echo "Running Gradle build"
  displayName: 'Run Gradle Build'
  
- script: ./gradlew test  # Adjust this command based on your project setup
  displayName: 'Run Unit Tests'

- script: ./gradlew assembleDebug  # Adjust this command for your build variant
  displayName: 'Assemble Debug Build'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/app/build/outputs/apk/debug'
    artifactName: 'debug-apk'
