trigger:
- master

pool:
  name: Bharath-Finance-Pool
  vmImage: 'macOS-latest' # Use macOS or another suitable image for Android development

variables:
  JAVA_HOME: $(JAVA_HOME_8_X64)
  JAVA_HOME_8_X64: /usr/lib/jvm/java-8-openjdk-amd64
  ANDROID_SDK_ROOT: /opt/android-sdk 

steps:
- script: |
    chmod +x ./gradlew
    ./gradlew assembleRelease
  displayName: 'Build Android App'

# - task: CopyFiles@2
#   inputs:
#     sourceFolder: '$(Build.SourcesDirectory)/app/build/outputs/apk/release/'
#     contents: '**/*.apk'
#     targetFolder: '$(Build.ArtifactStagingDirectory)'

# - task: PublishPipelineArtifact@1
#   inputs:
#     targetPath: '$(Build.ArtifactStagingDirectory)'
#     artifactName: 'apk'

- script: |
    ls -R '$(Build.SourcesDirectory)/app/build/outputs/apk/release'
  displayName: Source Directory Path


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/app/build/outputs/apk/release/'
    Contents: '**/*.apk'
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'apk'

- script: |
    ls -R '$(Build.ArtifactStagingDirectory)'
  displayName: List Artifact Staging Directory Contents

    
- task: UniversalPackages@0
  displayName: Publish a Universal Package
  inputs:
    command: publish
    publishDirectory: '$(Build.SourcesDirectory)/app/build/outputs/apk/release/app-release-unsigned.apk'
    vstsFeedPublish: 'Bharath-Finance/Bharat-fin-artifact'
    vstsFeedPackagePublish: 'app-release-unsigned.apk'
    versionOption: minor
    versionPublish: '1.1.0'
    packagePublishDescription: 'Publishing the build artifact to azure artifacts'


# - task: AppCenterDistribute@3
#   inputs:
#     serverEndpoint: 'app-center'
#     appSlug: 'poc_apk'
#     appFile: '$(Build.SourcesDirectory)/app/build/outputs/apk/release/app-release-unsigned.apk'
#     symbolsOption: 'Android'
#     releaseNotesOption: 'input'
#     releaseNotesInput: 'Release notes for this version.'
#     destinationType: 'groups'
#     distributionGroupId: 'Bharath-finance-poc'
    
