trigger:
- master

pool:
  name: Bharath-Finance-Pool
  vmImage: 'macOS-latest' # Use macOS or another suitable image for Android development

variables:
  JAVA_HOME: $(JAVA_HOME_8_X64)
  JAVA_HOME_8_X64: /usr/lib/jvm/java-8-openjdk-amd64
  ANDROID_SDK_ROOT: /opt/android-sdk 

steps:



# - script: |
#     chmod +x ./gradlew
#     ./gradlew assembleRelease
#   displayName: 'Build Android App'


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/app/build/outputs/apk/release/'
    Contents: '**/*.apk'
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'apk'


- task: AppCenterDistribute@3
  inputs:
    echo 'Hello'
    serverEndpoint: 'app-center'
    echo 'entered app-center'
    appSlug: 'Bharath-Finance'
    echo 'set up app slug'
    appFile: '$(Build.SourcesDirectory)/app/build/outputs/apk/release/app-release-unsigned.apk'
    echo 'taken apk file'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: 'Release notes for this version.'
    echo 'entered group'
    destinationType: 'groups'
    echo 'deploy distribution'
    distributionGroupId: 'poc-finance'
    echo 'success'
    ownerName: 'shital'
  displayName: 'Distribute App to App Center'
